--- 
:realname: arcanine-bot
:ident: arcanine
:nick: arcanine
:password: changeMe
:servers: 
- :channels: 
  - "#botters"
  - "#botters-test"
  :host: irc.freenode.net
  :name: freenode
  :port: 6667
